// Auth
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

// Novels
export const SET_AUTOCOMPLETE_RESULTS = 'SET_AUTOCOMPLETE_RESULTS';
export const SET_SELECTED_NOVEL = 'SET_SELECTED_NOVEL';
export const CLEAR_SELECTED_NOVEL = 'CLEAR_SELECTED_NOVEL';
export const SET_AWARDS = 'SET_AWARDS';
export const CLEAR_AWARDS = 'CLEAR_AWARDS';
export const CREATE_RECORD = 'CREATE_RECORD';
export const READ_RECORDS = 'READ_RECORD';
export const UPDATE_RECORD = 'UPDATE_RECORD';
export const DELETE_RECORD = 'DELETE_RECORD';
export const CLEAR_RECORDS = 'CLEAR_RECORDS';
export const SET_LOADING = 'SET_LOADING';
